name: ga-hands-on-day5
on:
  push:
    branches:
        development
env:
  VERSION: ${{vars.VERSION}}
  PRODUCTION_API_URL: ${{vars.PRODUCTION_API_URL}}
  STAGING_API_URL: ${{vars.STAGING_API_URL}}
jobs:
  build-web-app: 
    environment: Staging
    runs-on: ubuntu-latest
    steps:
      - name: deploy to Staging
        run: |
          echo "Deploying to Staging" 
          echo "staging api: ${{env.STAGING_API_URL}}"
          echo "production api: ${{env.PRODUCTION_API_URL}}"
          echo "version: ${{env.VERSION}}"